"""Added a deleted_at field in Vm table

Revision ID: 16740cdbdd7c
Revises: 
Create Date: 2018-03-15 11:35:59.559663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16740cdbdd7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'deleted_at')
    # ### end Alembic commands ###
