<<<<<<< d9efd336f3872be8f153d58d949a089f61376283
"""Add a new column deleted_at in table vm
=======
"""empty message
>>>>>>> Create a new migration for a change in Vm table

Revision ID: ac40d51a4114
Revises: 45b003a9a66f
Create Date: 2018-03-20 15:23:15.806539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac40d51a4114'
down_revision = '45b003a9a66f'
branch_labels = None
depends_on = None


def upgrade():
<<<<<<< d9efd336f3872be8f153d58d949a089f61376283
    op.add_column('vm', sa.Column('deleted_at', sa.DateTime(), nullable=True))


def downgrade():
    op.drop_column('vm', 'deleted_at')
=======
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'deleted_at')
    # ### end Alembic commands ###
>>>>>>> Create a new migration for a change in Vm table
